# --- Database Connection ---
spring.datasource.driver-class-name=org.postgresql.Driver

# Environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# --- Connection Pool ---
# Maximum 1 connection to the DB per instance of application
# Basically, Hibernate, reuses the same connection for every query,
# even when the query is done. This is better for resources. This pattern
# is named Session per Request.
spring.datasource.hikari.maximum-pool-size=1

# --- Hibernate / JPA Settings ---
# The type of SQL language is used (In this case Postgresql)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# For debugging
spring.jpa.show-sql=true

# Creates or updates tables on startup of the application
spring.jpa.hibernate.ddl-auto=update

# images path
file.upload-dir=./uploads/images
